演習問題6　問題5(1)

CREATE TABLE LINK (
  LINKID VARCHAR(5) PRIMARY KEY,
  CATEGORYID VARCHAR(3) NOT NULL,
  LINKNAME VARCHAR(40) NOT NULL,
  URL VARCHAR(200) NOT NULL
);

CREATE TABLE LINKCATEGORY (
  CATEGORYID VARCHAR(3) PRIMARY KEY,
  CATEGORYNAME VARCHAR(40) NOT NULL
);
