演習問題6　問題5(2)

INSERT INTO LINK(LINKID, CATEGORYID, LINKNAME, URL) VALUES('00001', '001', 'サン・マイクロシステムズ', 'http://jp.sun.com/java/');
INSERT INTO LINK(LINKID, CATEGORYID, LINKNAME, URL) VALUES('00002', '002', 'SQL講座', 'http://www.pursue.ne.jp/SQLDoc/SQL.htm');
INSERT INTO LINK(LINKID, CATEGORYID, LINKNAME, URL) VALUES('00003', '001', '@IT Javaソリューション', 'http://www.atmarkit.co.jp/fjava/');
INSERT INTO LINK(LINKID, CATEGORYID, LINKNAME, URL) VALUES('00004', '003', 'UMLチュートリアル', 'http://uml.ogis-ri.co.jp/tutorial/index.htm');

INSERT INTO LINKCATEGORY(CATEGORYID, CATEGORYNAME) VALUES('001', 'Java');
INSERT INTO LINKCATEGORY(CATEGORYID, CATEGORYNAME) VALUES('002', 'SQL');
INSERT INTO LINKCATEGORY(CATEGORYID, CATEGORYNAME) VALUES('003', 'UML');